class_name AH extends Node

enum abs {Stench,Drizzle,SpeedBoost,Sturdy,BattleArmor,Damp,Limber,SandVeil,Static,VoltAbsorb,WaterAbsorb,Oblivious,CloudNine,CompoundEyes,Insomnia,ColorChange,Immunity,FlashFire,ShieldDust,OwnTempo,SuctionCups,Intimidate,ShadowTag,RoughSkin,WonderGuard,Levitate,EffectSpore,Synchronize,ClearBody,NaturalCure,LightningRod,SereneGrace,SwiftSwim,Chlorophyll,Illuminate,Trace,HugePower,PoisonPoint,InnerFocus,MagmaArmor,WaterVeil,MagnetPull,Soundproof,RainDish,SandStream,Pressure,ThickFat,EarlyBird,FlameBody,RunAway,KeenEye,HyperCutter,Pickup,Truant,Hustle,CuteCharm,Plus,Minus,Forecast,StickyHold,ShedSkin,Guts,MarvelScale,LiquidOoze,Overgrow,Blaze,Torrent,Swarm,RockHead,Drought,ArenaTrap,VitalSpirit,WhiteSmoke,PurePower,ShellAmor,AirLock,TangledFeet,MotorDrive,Rivalry,Steadfast,SnowClock,Gluttony,StrictPatrol,StrongJaw}
#Drizzle,,,CloudNine,,OwnTempo,SuctionCups,Intimidate,ShadowTag,RoughSkin,WonderGuard,Levitate,EffectSpore,Synchronize,ClearBody,NaturalCure,LightningRod,SereneGrace,SwiftSwim,Chlorophyll,Illuminate,Trace,HugePower,PoisonPoint,InnerFocus,MagmaArmor,WaterVeil,MagnetPull,Soundproof,RainDish,SandStream,Pressure,ThickFat,EarlyBird,FlameBody,RunAway,KeenEye,HyperCutter,Pickup,Truant,Hustle,CuteCharm,Plus,Minus,Forecast,StickyHold,ShedSkin,Guts,MarvelScale,LiquidOoze,Overgrow,Blaze,Torrent,Swarm,RockHead,Drought,ArenaTrap,VitalSpirit,WhiteSmoke,PurePower,ShellAmor,AirLock,TangledFeet,MotorDrive,Rivalry,Steadfast,SnowClock,Gluttony
const desc = {
    abs.Stench:"This Pokemon smells so bad it may cause its opponent to flinch, and makes pests stay away!",
    abs.Drizzle:"This Pokemon can make it rain whenever they please.",
    abs.SpeedBoost:"This Pokemon keeps getting faster and faster the more it stays on task!",
    abs.Sturdy:"This Pokemon will hang on to its last bit of HP when hit wit an attack that would otherwise KO it",
    abs.BattleArmor:"This Pokemon cannot be critically hit.",
    abs.Damp:"This Pokemon can water plants without a water type move.",
    abs.Limber:"This Pokemon cannot be paralyzed, and is very good at dancing!",
    abs.SandVeil:"This Pokemon excels in sandstorms and mining dust clouds!",
    abs.Static:"This Pokemon may paralyze other Pokemon on contact, can can generate electricity without an electric type move",
    abs.VoltAbsorb:"This Pokemon absorbs HP and energy from electricity.",
    abs.WaterAbsorb:"This Pokemon absorbs HP from water.",
    abs.Oblivious:"This Pokemon is oblivious to various factors around it.",
    abs.CloudNine:"This Pokemon is not affected by weather.",
    abs.CompoundEyes:"This Pokemon has extremely good eyesight, good for foraging.",
    abs.Insomnia:"This Pokemon sleeps less than it should!",
    abs.ColorChange:"",
    abs.Immunity:"This Pokemon cannot be poisoned.",
    abs.FlashFire:"This Pokemon absorbs the power of fire, recovering energy from fire.",
    abs.ShieldDust:"This Pokemon is guarded against additional effects from attacks.",
    abs.OwnTempo:"This Pokemon cannot be confused, but it is a terrible dancer.",
    abs.SuctionCups:"",
    abs.Intimidate:"This Pokemon's ferocity lowers it's enemy's attack upon entering battle.",
    abs.ShadowTag:"You cannot run from this Pokemon!",
    abs.RoughSkin:"This Pokemon's rough skin damages its opponent on contact",
    abs.WonderGuard:"",
    abs.Levitate:"",
    abs.EffectSpore:"",
    abs.Synchronize:"",
    abs.ClearBody:"",
    abs.NaturalCure:"",
    abs.LightningRod:"",
    abs.SereneGrace:"",
    abs.SwiftSwim:"",
    abs.Chlorophyll:"",
    abs.Illuminate:"",
    abs.Trace:"",
    abs.HugePower:"",
    abs.PoisonPoint:"",
    abs.InnerFocus:"",
    abs.MagmaArmor:"",
    abs.WaterVeil:"",
    abs.MagnetPull:"",
    abs.Soundproof:"",
    abs.RainDish:"",
    abs.SandStream:"",
    abs.Pressure:"",
    abs.ThickFat:"",
    abs.EarlyBird:"",
    abs.FlameBody:"",
    abs.RunAway:"",
    abs.KeenEye:"",
    abs.HyperCutter:"",
    abs.Pickup:"",
    abs.Truant:"",
    abs.Hustle:"",
    abs.CuteCharm:"",
    abs.Plus:"",
    abs.Minus:"",
    abs.Forecast:"",
    abs.StickyHold:"",
    abs.ShedSkin:"",
    abs.Guts:"",
    abs.MarvelScale:"",
    abs.LiquidOoze:"",
    abs.Overgrow:"",
    abs.Blaze:"",
    abs.Torrent:"",
    abs.Swarm:"",
    abs.RockHead:"",
    abs.Drought:"",
    abs.ArenaTrap:"",
    abs.VitalSpirit:"",
    abs.WhiteSmoke:"",
    abs.PurePower:"",
    abs.ShellAmor:"",
    abs.AirLock:"",
    abs.TangledFeet:"",
    abs.MotorDrive:"",
    abs.Rivalry:"",
    abs.Steadfast:"",
    abs.SnowClock:"",
    abs.Gluttony:"",
    abs.StrictPatrol:"Greatly reduces number of pests.",
    abs.StrongJaw:"Increases the power of biting moves"
}
